In [ ]:
print("dhool peta")

dhool peta

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
data=[1,2,3,4,5]
s=pd.Series(data)
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
s=pd.Series([1,2,3,4,5])
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
#we can ch
s=pd.Series([1,2,3,4,5],index=["a","b","c","d","e"])
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
# we can also pass dictionary in series keys=indexes, values=values
s=pd.Series({'a':1,'b':2,'c':3,'d':4,'e':5})
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
#accessing using index positions
data=['g','e','e','k','s','f','o','r','g','e','e','k','s']
ser=pd.Series(data)
print(ser[:6])
print(ser[:2])
print(ser[-2:])
print(ser[2:])
print(ser[:-2])
print(ser[::-1])

0    g
1    e
2    e
3    k
4    s
5    f
dtype: object
0    g
1    e
dtype: object
11    k
12    s
dtype: object
2     e
3     k
4     s
5     f
6     o
7     r
8     g
9     e
10    e
11    k
12    s
dtype: object
0     g
1     e
2     e
3     k
4     s
5     f
6     o
7     r
8     g
9     e
10    e
dtype: object
12    s
11    k
10    e
9     e
8     g
7     r
6     o
5     f
4     s
3     k
2     e
1     e
0     g
dtype: object

In [ ]:
#updating a series
data=['g','e','e','k','s','f','o','r','g','e','z','k','s']
ser=pd.Series(data)
ser["z"]="e"
print(ser)

0     g
1     e
2     e
3     k
4     s
5     f
6     o
7     r
8     g
9     e
10    z
11    k
12    s
z     e
dtype: object

In [ ]:
data=['g','e','e','k','s','f','o','r','g','e','z','k','s']
ser=pd.Series(data)
(ser[ser=='z'].index)='e'
print(ser)

TypeError: Index(...) must be called with a collection of some kind, 'e' was passed

In [ ]:
#deleting elements
ser.drop(4)
print(ser)
ser=ser.drop(4)
print(ser)

0     g
1     e
2     e
3     k
4     s
5     f
6     o
7     r
8     g
9     e
10    z
11    k
12    s
dtype: object
0     g
1     e
2     e
3     k
5     f
6     o
7     r
8     g
9     e
10    z
11    k
12    s
dtype: object

In [ ]:
stu_marks={101:78,102:85,103:92,104:67,105:88}
s=pd.Series(stu_marks)
print(s[103])
s[104]=75
print(s)
s=s.drop(102)
print(s)
s[106]=80
print(s)

92
101    78
102    85
103    92
104    75
105    88
dtype: int64
101    78
103    92
104    75
105    88
dtype: int64
101    78
103    92
104    75
105    88
106    80
dtype: int64

In [ ]:
employees=[1001,1002,1003,1004,1005]
salary=[35000,42000,38000,50000,45000]
s=pd.Series(salary,index=employees)
'''
print(s)
s[1003]=48000
print(s)
s[1006]=55000
print(s)
s=s.drop(1002)
print(s)
print(s[:3])
print(s)'''

1001    35000
1002    42000
1003    38000
1004    50000
1005    45000
dtype: int64

In [ ]:
product_id=['P101','P102','P103','P104','P105']
Price=[500,600,1200,900,1500]
store=pd.Series(Price,index=product_id)

In [ ]:
print(store['P103'])

1200

In [ ]:
store['P102']=800
print(store)

P101     500
P102     800
P103    1200
P104     900
P105    1500
dtype: int64

In [ ]:
store=store.drop('P103')
print(store)

P101     500
P102     800
P104     900
P105    1500
dtype: int64

In [ ]:
store['P106']=2000
print(store)

P101     500
P102     800
P104     900
P105    1500
P106    2000
dtype: int64

**Day-2**

In [ ]:

#dataframes creation
#using list
import pandas as pd
data=[
    ["Ravi",22,30000],
    ["Priya",24,40000],
    ["Arun",21,28000]
]
df=pd.DataFrame(data,columns=["Name","Age","Salary"])
print(df)

    Name  Age  Salary
0   Ravi   22   30000
1  Priya   24   40000
2   Arun   21   28000

In [ ]:
#using tuple
data=(
    ("Ravi",22,30000),
    ("Priya",24,40000),
    ("Arun",21,28000)
)
df=pd.DataFrame(data,columns=("Name","Age","Salary"))
print(df)

    Name  Age  Salary
0   Ravi   22   30000
1  Priya   24   40000
2   Arun   21   28000

In [ ]:
#using dictionary
data={
    "Names":["Ganny","Balaji","Yaswanth","Karthik"],
    "Age":[23,23,21,21],
    "Salary":[51000,55000,49000,48000]
}
df=pd.DataFrame(data)
print(df)

      Names  Age  Salary
0     Ganny   23   51000
1    Balaji   23   55000
2  Yaswanth   21   49000
3   Karthik   21   48000

In [ ]:
#sales and profit of every month in first 6 months of year
data={
    "Month":["January","February","March","April","may","June"],
    "Sales":[10000,20000,30000,50000,100000,200000],
    "Profit":[0,10000,10000,20000,50000,100000]
}
report=pd.DataFrame(data,index=[1,2,3,4,5,6])
print(report)

      Month   Sales  Profit
1   January   10000       0
2  February   20000   10000
3     March   30000   10000
4     April   50000   20000
5       may  100000   50000
6      June  200000  100000

In [ ]:
# creating dataframe with set
my_set={100,200,300,400}
my_set=list(my_set)
df=pd.DataFrame(my_set,columns=["values"])
print(df)

   values
0     200
1     100
2     400
3     300

In [ ]:
#converting a single-Series into Dataframe
s=pd.Series([1,2,3,4],name="Numbers")
df=s.to_frame()
print(df)

   Numbers
0        1
1        2
2        3
3        4

In [ ]:
#converting a multiple-Series into Dataframe
s=pd.Series([1,2,3,4])
s2=pd.Series([100,99,98,97])
s3=pd.Series([200,199,198,197])
d={
    "Subject-1":s,
    "Subject-2":s2,
    "Subject-3":s3
}
df=pd.DataFrame(d)
print(df)

   Subject-1  Subject-2  Subject-3
0          1        100        200
1          2         99        199
2          3         98        198
3          4         97        197

In [ ]:
#rename the column name
s=pd.Series([1,2,3,4],name="Numbers")
df=s.to_frame()
df.columns=["digits"]
print(df)

   digits
0       1
1       2
2       3
3       4

In [ ]:
#renaming multiple column names
s=pd.Series([1,2,3,4])
s2=pd.Series([100,99,98,97])
s3=pd.Series([200,199,198,197])
d={
    "Subject-1":s,
    "Subject-2":s2,
    "Subject-3":s3
}
df=pd.DataFrame(d)
df.columns=("Apptitude","Python","DA")
print(df)

   Apptitude  Python   DA
0          1     100  200
1          2      99  199
2          3      98  198
3          4      97  197

In [ ]:
#assigning column name
df=pd.DataFrame([
    [1,2],
    [3,4]]
)
df.columns=["A","B"]
print(df)

   A  B
0  1  2
1  3  4

In [ ]:
df.rename(columns={'A':'Alpha','B':'Beta'},inplace=True)
print(df)

   Alpha  Beta
0      1     2
1      3     4

In [ ]:
#viewing the dataframe
#head()
s=pd.Series([1,2,3,4,5,6,7,8,9])
s2=pd.Series([100,99,98,97,96,95,94,93,92])
s3=pd.Series([200,199,198,197,196,195,194,193,192])
d={
    "Subject-1":s,
    "Subject-2":s2,
    "Subject-3":s3
}
df=pd.DataFrame(d)
df.columns=("Apptitude","Python","DA")
print(df.head())
print(df.tail())
print(df.head(2))
print(df.tail(3))
print(len(df))
print(df.shape)
print(df.index)
print(df.values)

   Apptitude  Python   DA
0          1     100  200
1          2      99  199
2          3      98  198
3          4      97  197
4          5      96  196
   Apptitude  Python   DA
4          5      96  196
5          6      95  195
6          7      94  194
7          8      93  193
8          9      92  192
   Apptitude  Python   DA
0          1     100  200
1          2      99  199
   Apptitude  Python   DA
6          7      94  194
7          8      93  193
8          9      92  192
9
(9, 3)
RangeIndex(start=0, stop=9, step=1)
[[  1 100 200]
 [  2  99 199]
 [  3  98 198]
 [  4  97 197]
 [  5  96 196]
 [  6  95 195]
 [  7  94 194]
 [  8  93 193]
 [  9  92 192]]

In [ ]:
'''
data=[
    ["Ravi",22,"pakistan",30000],
    ["Priya",24,"afganistan",40000],
    ["Arun",21,"Dubai-Emrates",28000],
    ["Ganny-hangover-guy",23,"Vizag",100000],
    ["Ganny-good-boy",23,"Vizag",500000]
]
df=pd.DataFrame(data,columns=["Name","Age","City","Salary"])
print(df)

#using dictionary
product_info={
    "Product":["oppo","vivo","apple","samsung","micromax"],
    "Category":["mobile-1","mobile-2","mobile-3","mobile-4","mobile-5"],
    "Price":[500000,10000,2000,50000,1000000],
    "Quantity":[1,2,3,4,5]
}
report=pd.DataFrame(product_info)
print(report)'''

    Product  Category    Price  Quantity
0      oppo  mobile-1   500000         1
1      vivo  mobile-2    10000         2
2     apple  mobile-3     2000         3
3   samsung  mobile-4    50000         4
4  micromax  mobile-5  1000000         5

**DAY-3**

In [ ]:
#selecting and filtering
import pandas as pd
data={
    "Name":["Ravi","Priya","Arun","Sneha","Kiran","Anjali","Vikram","Meena"],
    "Age":[22,24,21,25,23,26,20,27],
    "City":["Hyd","Chennai","Banglore","Hyd","Mumbai","Chennai","Banglore","Mumbai"],
    "Salary":[30000,40000,28000,50000,35000,45000,25000,55000]
}

df=pd.DataFrame(data,index=[101,102,103,104,105,106,107,108])

In [ ]:
#viewing data
print(df.head())
print("-----------------------------------------------------------------------")
print(df.tail())
print("-----------------------------------------------------------------------")
print(df.info())
print("-----------------------------------------------------------------------")
print(df.describe())
print("-----------------------------------------------------------------------")
print(len(df))
print("-----------------------------------------------------------------------")
print(df.shape)
print("-----------------------------------------------------------------------")
print(df.index)
print("-----------------------------------------------------------------------")

      Name  Age      City  Salary
101   Ravi   22       Hyd   30000
102  Priya   24   Chennai   40000
103   Arun   21  Banglore   28000
104  Sneha   25       Hyd   50000
105  Kiran   23    Mumbai   35000
-----------------------------------------------------------------------
       Name  Age      City  Salary
104   Sneha   25       Hyd   50000
105   Kiran   23    Mumbai   35000
106  Anjali   26   Chennai   45000
107  Vikram   20  Banglore   25000
108   Meena   27    Mumbai   55000
-----------------------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 101 to 108
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    8 non-null      object
 1   Age     8 non-null      int64
 2   City    8 non-null      object
 3   Salary  8 non-null      int64
dtypes: int64(2), object(2)
memory usage: 320.0+ bytes
None
-----------------------------------------------------------------------
            Age        Salary
count   8.00000      8.000000
mean   23.50000  38500.000000
std     2.44949  10862.780491
min    20.00000  25000.000000
25%    21.75000  29500.000000
50%    23.50000  37500.000000
75%    25.25000  46250.000000
max    27.00000  55000.000000
-----------------------------------------------------------------------
8
-----------------------------------------------------------------------
(8, 4)
-----------------------------------------------------------------------
Index([101, 102, 103, 104, 105, 106, 107, 108], dtype='int64')
-----------------------------------------------------------------------

In [ ]:
print(df[["Name","Age"]])

       Name  Age
101    Ravi   22
102   Priya   24
103    Arun   21
104   Sneha   25
105   Kiran   23
106  Anjali   26
107  Vikram   20
108   Meena   27

In [ ]:
print(df[["Name","Age","City","Salary"]])

       Name  Age      City  Salary
101    Ravi   22       Hyd   30000
102   Priya   24   Chennai   40000
103    Arun   21  Banglore   28000
104   Sneha   25       Hyd   50000
105   Kiran   23    Mumbai   35000
106  Anjali   26   Chennai   45000
107  Vikram   20  Banglore   25000
108   Meena   27    Mumbai   55000

In [ ]:
(df.iloc[0:3])

      Name  Age      City  Salary
101   Ravi   22       Hyd   30000
102  Priya   24   Chennai   40000
103   Arun   21  Banglore   28000

In [ ]:
(df.loc[103:105])

      Name  Age      City  Salary
103   Arun   21  Banglore   28000
104  Sneha   25       Hyd   50000
105  Kiran   23    Mumbai   35000

In [ ]:
#condition based filtering
print("------------------------------------------------------------------------")
print(df["Salary"]>45000) #here we can see True/False
print("------------------------------------------------------------------------")
df[df["Salary"]<45000] #here we can see actual values satisfing condition

------------------------------------------------------------------------
101    False
102    False
103    False
104     True
105    False
106    False
107    False
108     True
Name: Salary, dtype: bool
------------------------------------------------------------------------

       Name  Age      City  Salary
101    Ravi   22       Hyd   30000
102   Priya   24   Chennai   40000
103    Arun   21  Banglore   28000
105   Kiran   23    Mumbai   35000
107  Vikram   20  Banglore   25000

In [ ]:
#task
import pandas as pd

data = {
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": ["Aarav", "Priya", "Rahul", "Sneha", "Arjun",
             "Divya", "Kiran", "Ananya", "Rohit", "Meena"],
    "Age": [20, 21, 19, 22, 20, 21, 23, 19, 22, 20],
    "Course": ["Python", "Power BI", "Python", "Excel", "Python",
               "Power BI", "Excel", "Python", "Power BI", "Excel"],
    "Marks": [85, 78, 92, 67, 88, 74, 81, 95, 69, 90],
    "Attendance": [92, 85, 96, 78, 89, 82, 91, 98, 75, 94],
    "City": ["Hyderabad", "Chennai", "Bangalore", "Hyderabad", "Pune",
             "Chennai", "Hyderabad", "Bangalore", "Pune", "Hyderabad"]
}

df = pd.DataFrame(data)
print(df)

   Student_ID    Name  Age    Course  Marks  Attendance       City
0         101   Aarav   20    Python     85          92  Hyderabad
1         102   Priya   21  Power BI     78          85    Chennai
2         103   Rahul   19    Python     92          96  Bangalore
3         104   Sneha   22     Excel     67          78  Hyderabad
4         105   Arjun   20    Python     88          89       Pune
5         106   Divya   21  Power BI     74          82    Chennai
6         107   Kiran   23     Excel     81          91  Hyderabad
7         108  Ananya   19    Python     95          98  Bangalore
8         109   Rohit   22  Power BI     69          75       Pune
9         110   Meena   20     Excel     90          94  Hyderabad

In [ ]:
#1
print(df)

   Student_ID    Name  Age    Course  Marks  Attendance       City
0         101   Aarav   20    Python     85          92  Hyderabad
1         102   Priya   21  Power BI     78          85    Chennai
2         103   Rahul   19    Python     92          96  Bangalore
3         104   Sneha   22     Excel     67          78  Hyderabad
4         105   Arjun   20    Python     88          89       Pune
5         106   Divya   21  Power BI     74          82    Chennai
6         107   Kiran   23     Excel     81          91  Hyderabad
7         108  Ananya   19    Python     95          98  Bangalore
8         109   Rohit   22  Power BI     69          75       Pune
9         110   Meena   20     Excel     90          94  Hyderabad

In [ ]:
#2
df.head()

   Student_ID   Name  Age    Course  Marks  Attendance       City
0         101  Aarav   20    Python     85          92  Hyderabad
1         102  Priya   21  Power BI     78          85    Chennai
2         103  Rahul   19    Python     92          96  Bangalore
3         104  Sneha   22     Excel     67          78  Hyderabad
4         105  Arjun   20    Python     88          89       Pune

In [ ]:
#3
df.tail(3)

   Student_ID    Name  Age    Course  Marks  Attendance       City
7         108  Ananya   19    Python     95          98  Bangalore
8         109   Rohit   22  Power BI     69          75       Pune
9         110   Meena   20     Excel     90          94  Hyderabad

In [ ]:
#4
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Course      10 non-null     object
 4   Marks       10 non-null     int64
 5   Attendance  10 non-null     int64
 6   City        10 non-null     object
dtypes: int64(4), object(3)
memory usage: 692.0+ bytes

       Student_ID        Age      Marks  Attendance
count    10.00000  10.000000  10.000000   10.000000
mean    105.50000  20.700000  81.900000   88.000000
std       3.02765   1.337494   9.734817    7.745967
min     101.00000  19.000000  67.000000   75.000000
25%     103.25000  20.000000  75.000000   82.750000
50%     105.50000  20.500000  83.000000   90.000000
75%     107.75000  21.750000  89.500000   93.500000
max     110.00000  23.000000  95.000000   98.000000

In [ ]:
#5
df["Name"]

0     Aarav
1     Priya
2     Rahul
3     Sneha
4     Arjun
5     Divya
6     Kiran
7    Ananya
8     Rohit
9     Meena
Name: Name, dtype: object

In [ ]:
#6
df[["Name","Course","Marks"]]

     Name    Course  Marks
0   Aarav    Python     85
1   Priya  Power BI     78
2   Rahul    Python     92
3   Sneha     Excel     67
4   Arjun    Python     88
5   Divya  Power BI     74
6   Kiran     Excel     81
7  Ananya    Python     95
8   Rohit  Power BI     69
9   Meena     Excel     90

In [ ]:
#7
df[["Student_ID","Age","Attendance","City"]].loc[0:9]

   Student_ID  Age  Attendance       City
0         101   20          92  Hyderabad
1         102   21          85    Chennai
2         103   19          96  Bangalore
3         104   22          78  Hyderabad
4         105   20          89       Pune
5         106   21          82    Chennai
6         107   23          91  Hyderabad
7         108   19          98  Bangalore
8         109   22          75       Pune
9         110   20          94  Hyderabad

In [ ]:
#8
df.loc[2:6]

   Student_ID   Name  Age    Course  Marks  Attendance       City
2         103  Rahul   19    Python     92          96  Bangalore
3         104  Sneha   22     Excel     67          78  Hyderabad
4         105  Arjun   20    Python     88          89       Pune
5         106  Divya   21  Power BI     74          82    Chennai
6         107  Kiran   23     Excel     81          91  Hyderabad

In [ ]:
#9
df[["Name","Course","Marks"]].loc[1:5]

    Name    Course  Marks
1  Priya  Power BI     78
2  Rahul    Python     92
3  Sneha     Excel     67
4  Arjun    Python     88
5  Divya  Power BI     74

In [ ]:
#10
df[["Name","Marks",'City']].iloc[7]

Name        Ananya
Marks           95
City     Bangalore
Name: 7, dtype: object

In [ ]:
#11
df.iloc[0:5,:4]

   Student_ID   Name  Age    Course
0         101  Aarav   20    Python
1         102  Priya   21  Power BI
2         103  Rahul   19    Python
3         104  Sneha   22     Excel
4         105  Arjun   20    Python

In [ ]:
#12
df[["Name","Course","Marks"]].iloc[2:7]

    Name    Course  Marks
2  Rahul    Python     92
3  Sneha     Excel     67
4  Arjun    Python     88
5  Divya  Power BI     74
6  Kiran     Excel     81

In [ ]:
#13
df.iloc[-3:]

   Student_ID    Name  Age    Course  Marks  Attendance       City
7         108  Ananya   19    Python     95          98  Bangalore
8         109   Rohit   22  Power BI     69          75       Pune
9         110   Meena   20     Excel     90          94  Hyderabad

In [ ]:
#14
df[df["Marks"]>80]

   Student_ID    Name  Age  Course  Marks  Attendance       City
0         101   Aarav   20  Python     85          92  Hyderabad
2         103   Rahul   19  Python     92          96  Bangalore
4         105   Arjun   20  Python     88          89       Pune
6         107   Kiran   23   Excel     81          91  Hyderabad
7         108  Ananya   19  Python     95          98  Bangalore
9         110   Meena   20   Excel     90          94  Hyderabad

In [ ]:
#15
df[(df["Marks"]>80) & (df['Attendance']>90)]

   Student_ID    Name  Age  Course  Marks  Attendance       City
0         101   Aarav   20  Python     85          92  Hyderabad
2         103   Rahul   19  Python     92          96  Bangalore
6         107   Kiran   23   Excel     81          91  Hyderabad
7         108  Ananya   19  Python     95          98  Bangalore
9         110   Meena   20   Excel     90          94  Hyderabad

**DAY-4**

In [ ]:
#manipulating data
import pandas as pd

sales = pd.Series(
    [5000, 7000, None, 9000, 8000, 10000, None],
    index=[
        "Monday", "Tuesday", "Wednesday", "Thursday",
        "Friday", "Saturday", "Sunday"
    ]
)

print(sales)

Monday        5000.0
Tuesday       7000.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
dtype: float64

In [ ]:
sales.min()

5000.0

In [ ]:
sales.max()

10000.0

In [ ]:
sales.mean()

np.float64(7800.0)

In [ ]:
sales.sum()

np.float64(39000.0)

In [ ]:
sales.var()

3700000.0

In [ ]:
sales.std()

1923.5384061671346

In [ ]:
print(sales.dtype)

float64

In [ ]:
#updating data
sales["Tuesday"]=9500
print(sales)

Monday        5000.0
Tuesday       9500.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
dtype: float64

In [ ]:
#adding data
sales["jan"]=7800
print(sales)

Monday        5000.0
Tuesday       9500.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
jan           7800.0
dtype: float64

In [ ]:
#deleting data
sales=sales.drop("Tuesday")
print(sales)

Monday        5000.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
jan           7800.0
dtype: float64

In [ ]:
print(sales+2000)
print(sales*2)

Monday        7000.0
Wednesday        NaN
Thursday     11000.0
Friday       10000.0
Saturday     12000.0
Sunday           NaN
jan           9800.0
dtype: float64
Monday       10000.0
Wednesday        NaN
Thursday     18000.0
Friday       16000.0
Saturday     20000.0
Sunday           NaN
jan          15600.0
dtype: float64

In [ ]:
s=pd.Series([1,2,3,4,5],index=[9,7,6,8,0])
s1=pd.Series([101,102,103,104,105]) #index=[901,902,903,904,905])
print(s,s1)

9    1
7    2
6    3
8    4
0    5
dtype: int64 0    101
1    102
2    103
3    104
4    105
dtype: int64

In [ ]:
#combining two series
d=pd.concat([s,s1])# here exact index will be concated
print(d)
c=pd.concat([s,s1],ignore_index=True)#to prevent excat index concated we can use
print(c)

0      1
1      2
2      3
3      4
4      5
5    101
6    102
7    103
8    104
9    105
dtype: int64

In [ ]:
import pandas as pd
data={
    "Name":["Ravi","Priya","Arun","Sneha","Kiran","Anjali","Vikram","Meena"],
    "Age":[22,24,21,25,23,26,20,27],
    "City":["Hyd","Chennai","Banglore","Hyd","Mumbai","Chennai","Banglore","Mumbai"],
    "Salary":[30000,40000,28000,50000,35000,45000,25000,55000]
}

df=pd.DataFrame(data,index=[101,102,103,104,105,106,107,108])

In [ ]:
#aggregations on dataframe
print(df["Age"].sum())
print(df["Salary"].sum())

188
308000

In [ ]:
print(df["Age"].min())
print(df["Salary"].min())

20
25000

In [ ]:
print(df["Age"].max())
print(df["Salary"].max())

27
55000

In [ ]:
print(df["Age"].mean())
print(df["Salary"].mean())

23.5
38500.0

In [ ]:
print(df["Age"].std())
print(df["Salary"].std())

2.449489742783178
10862.780491200216

In [ ]:
print(df["Age"].count())
print(df["Salary"].count())

8
8

In [ ]:
print(df["Age"].var())
print(df["Salary"].var())

6.0
118000000.0

In [ ]:
df["Bonus"]=df["Salary"]*0.1
print(df)

       Name  Age      City  Salary   Bonus
101    Ravi   22       Hyd   30000  3000.0
102   Priya   24   Chennai   40000  4000.0
103    Arun   21  Banglore   28000  2800.0
104   Sneha   25       Hyd   50000  5000.0
105   Kiran   23    Mumbai   35000  3500.0
106  Anjali   26   Chennai   45000  4500.0
107  Vikram   20  Banglore   25000  2500.0
108   Meena   27    Mumbai   55000  5500.0

In [ ]:
df["New_Salary"]=df["Salary"]+df["Bonus"]
print(df)

       Name  Age      City  Salary   Bonus  New_Salary
101    Ravi   22       Hyd   30000  3000.0     33000.0
102   Priya   24   Chennai   40000  4000.0     44000.0
103    Arun   21  Banglore   28000  2800.0     30800.0
104   Sneha   25       Hyd   50000  5000.0     55000.0
105   Kiran   23    Mumbai   35000  3500.0     38500.0
106  Anjali   26   Chennai   45000  4500.0     49500.0
107  Vikram   20  Banglore   25000  2500.0     27500.0
108   Meena   27    Mumbai   55000  5500.0     60500.0

In [ ]:
df["Age"]=df["Age"]+1
print(df)

       Name  Age      City  Salary   Bonus  New_Salary
101    Ravi   23       Hyd   30000  3000.0     33000.0
102   Priya   25   Chennai   40000  4000.0     44000.0
103    Arun   22  Banglore   28000  2800.0     30800.0
104   Sneha   26       Hyd   50000  5000.0     55000.0
105   Kiran   24    Mumbai   35000  3500.0     38500.0
106  Anjali   27   Chennai   45000  4500.0     49500.0
107  Vikram   21  Banglore   25000  2500.0     27500.0
108   Meena   28    Mumbai   55000  5500.0     60500.0

In [ ]:
df["New_Salary"]=df["New_Salary"]+500

In [ ]:
df.loc[df["Name"]=="Priya","City"]="Pune"
print(df)

       Name  Age      City  Salary   Bonus  New_Salary
101    Ravi   23       Hyd   30000  3000.0     33500.0
102   Priya   25      Pune   40000  4000.0     44500.0
103    Arun   22  Banglore   28000  2800.0     31300.0
104   Sneha   26       Hyd   50000  5000.0     55500.0
105   Kiran   24    Mumbai   35000  3500.0     39000.0
106  Anjali   27   Chennai   45000  4500.0     50000.0
107  Vikram   21  Banglore   25000  2500.0     28000.0
108   Meena   28    Mumbai   55000  5500.0     61000.0

In [ ]:
df.loc[df['City']=="Banglore","City"]="Hyd"
print(df)

       Name  Age     City  Salary   Bonus  New_Salary
101    Ravi   23      Hyd   30000  3000.0     33500.0
102   Priya   25     Pune   40000  4000.0     44500.0
103    Arun   22      Hyd   28000  2800.0     31300.0
104   Sneha   26      Hyd   50000  5000.0     55500.0
105   Kiran   24   Mumbai   35000  3500.0     39000.0
106  Anjali   27  Chennai   45000  4500.0     50000.0
107  Vikram   21      Hyd   25000  2500.0     28000.0
108   Meena   28   Mumbai   55000  5500.0     61000.0

In [ ]:
df.loc[df['City']=="Mumbai","Salary"]=df["Salary"]*1.05
print(df)

       Name  Age     City  Salary   Bonus  New_Salary
101    Ravi   23      Hyd   30000  3000.0     33500.0
102   Priya   25     Pune   40000  4000.0     44500.0
103    Arun   22      Hyd   28000  2800.0     31300.0
104   Sneha   26      Hyd   50000  5000.0     55500.0
105   Kiran   24   Mumbai   36750  3500.0     39000.0
106  Anjali   27  Chennai   45000  4500.0     50000.0
107  Vikram   21      Hyd   25000  2500.0     28000.0
108   Meena   28   Mumbai   57750  5500.0     61000.0

In [ ]:
df.loc[df['Salary']<45000,"Salary"]=600000
print(df)

       Name  Age     City  Salary   Bonus  New_Salary
101    Ravi   23      Hyd  600000  3000.0     33500.0
102   Priya   25     Pune  600000  4000.0     44500.0
103    Arun   22      Hyd  600000  2800.0     31300.0
104   Sneha   26      Hyd   50000  5000.0     55500.0
105   Kiran   24   Mumbai  600000  3500.0     39000.0
106  Anjali   27  Chennai   45000  4500.0     50000.0
107  Vikram   21      Hyd  600000  2500.0     28000.0
108   Meena   28   Mumbai   57750  5500.0     61000.0

In [ ]:
#deleting column
df.drop("Bonus",axis=1,inplace=True)
print(df)

       Name  Age     City  Salary  New_Salary
101    Ravi   23      Hyd  600000     33500.0
102   Priya   25     Pune  600000     44500.0
103    Arun   22      Hyd  600000     31300.0
104   Sneha   26      Hyd   50000     55500.0
105   Kiran   24   Mumbai  600000     39000.0
106  Anjali   27  Chennai   45000     50000.0
107  Vikram   21      Hyd  600000     28000.0
108   Meena   28   Mumbai   57750     61000.0

In [ ]:
df.drop(columns="New_Salary",inplace=True)
print(df)

       Name  Age     City  Salary
101    Ravi   23      Hyd  600000
102   Priya   25     Pune  600000
103    Arun   22      Hyd  600000
104   Sneha   26      Hyd   50000
105   Kiran   24   Mumbai  600000
106  Anjali   27  Chennai   45000
107  Vikram   21      Hyd  600000
108   Meena   28   Mumbai   57750

In [ ]:
df.dtypes

Name      object
Age        int64
City      object
Salary     int64
dtype: object

In [ ]:
df.describe()

            Age       Salary
count   8.00000       8.0000
mean   24.50000  394093.7500
std     2.44949  284198.3694
min    21.00000   45000.0000
25%    22.75000   55812.5000
50%    24.50000  600000.0000
75%    26.25000  600000.0000
max    28.00000  600000.0000

**Day-5**

In [ ]:
#loading data from csv,excel files
#to read from csv: df=pd.read_csv("csv-file-name-with-extension") or df=pd.read_

In [ ]:
#cleaning the data
#handling missing values
import pandas as pd

df = pd.DataFrame(
    [5000, 7000, None, 9000, 8000, 10000, None],
    index=[
        "Monday", "Tuesday", "Wednesday", "Thursday",
        "Friday", "Saturday", "Sunday"
    ]
)

In [ ]:
#identifing missing values
df.isna() #or df.isnull()

               0
Monday     False
Tuesday    False
Wednesday   True
Thursday   False
Friday     False
Saturday   False
Sunday      True

In [ ]:
#counting null values
df.isna().sum() #or df.isnull().sum()

0    2
dtype: int64

In [ ]:
#droping the null values
df.dropna()

                0
Monday     5000.0
Tuesday    7000.0
Thursday   9000.0
Friday     8000.0
Saturday  10000.0

In [ ]:
# filling missing values
df.fillna("no data")

                 0
Monday      5000.0
Tuesday     7000.0
Wednesday  no data
Thursday    9000.0
Friday      8000.0
Saturday   10000.0
Sunday     no data

In [ ]:
# replacing the missing values with aggergates

In [ ]:
employees = {
    "EmpID": [101, 102, 103, 104],
    "Name": ["Asha", None, "Meena", "sai"],
    "Department": ["Sales", "IT", "HR", None],
    "Salary": [45000, 60000, None, 89000]
}
I = [901, 902, 903, 904]
df_emp = pd.DataFrame(employees, index = I)

In [ ]:
df_emp.isna()

     EmpID   Name  Department  Salary
901  False  False       False   False
902  False   True       False   False
903  False  False       False    True
904  False  False        True   False

In [ ]:
df_emp.isna().sum()

EmpID         0
Name          1
Department    1
Salary        1
dtype: int64

In [ ]:
df_emp=df_emp.fillna({
    "Name":"Unknown",
    "Department": "Unknown",
    "Salary": 0
})

In [ ]:
print(df_emp)

     EmpID   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         IT  60000.0
903    103  Meena         HR      NaN
904    104    sai       None  89000.0

In [ ]:
df_emp["Salary"].fillna(df_emp["Salary"].max())

     EmpID   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         IT  60000.0
903    103  Meena         HR      NaN
904    104    sai       None  89000.0

In [ ]:
df_emp["Salary"].fillna(df_emp["Salary"].min())
print(df_emp)

     EmpID   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         IT  60000.0
903    103  Meena         HR      NaN
904    104    sai       None  89000.0

In [ ]:
df_emp["Salary"].fillna(df_emp["Salary"].mean())
print(df_emp)

901    45000.000000
902    60000.000000
903    64666.666667
904    89000.000000
Name: Salary, dtype: float64

In [ ]:
df_emp["Salary"].fillna(df_emp["Salary"].std())

901    45000.000000
902    60000.000000
903    22368.132093
904    89000.000000
Name: Salary, dtype: float64

In [ ]:
df_emp["Salary"].fillna(df_emp["Salary"].var())

901    4.500000e+04
902    6.000000e+04
903    5.003333e+08
904    8.900000e+04
Name: Salary, dtype: float64

In [ ]:
import pandas as pd
employees = {
    "EmpID": [101, 102, 103, 104],
    "Name": ["Asha", None, "Meena", "sai"],
    "Department": ["Sales", "IT", "HR", None],
    "Salary": [45000, 60000, None, 89000]
}
I = [901, 902, 903, 904]
df = pd.DataFrame(employees, index = I)

In [ ]:
print(df)

     EmpID   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         IT  60000.0
903    103  Meena         HR      NaN
904    104    sai       None  89000.0

In [ ]:
df.head(2)

     EmpID  Name Department   Salary
901    101  Asha      Sales  45000.0
902    102  None         IT  60000.0

In [ ]:
df.tail(2)

     EmpID   Name Department   Salary
903    103  Meena         HR      NaN
904    104    sai       None  89000.0

In [ ]:
df[["Name","Salary"]]

      Name   Salary
901   Asha  45000.0
902   None  60000.0
903  Meena      NaN
904    sai  89000.0

In [ ]:
df[df["EmpID"]==103]

     EmpID   Name Department  Salary
903    103  Meena         HR     NaN

In [ ]:
df[df["Salary"]>50000]

     EmpID  Name Department   Salary
902    102  None         IT  60000.0
904    104   sai       None  89000.0

In [ ]:
df[df["Department"]=="IT"]

     EmpID  Name Department   Salary
902    102  None         IT  60000.0

In [ ]:
df[(df["Name"].isna()) | (df["Department"]).isna()]

     EmpID  Name Department   Salary
902    102  None         IT  60000.0
904    104   sai       None  89000.0

In [ ]:
df.isna().sum()

EmpID         0
Name          1
Department    1
Salary        1
dtype: int64

In [ ]:
df.fillna(
    {
        "Name":"Unknown",
        "Salary":0,
        "Department":"Unknown"
    }
)

     EmpID     Name Department   Salary
901    101     Asha      Sales  45000.0
902    102  Unknown         IT  60000.0
903    103    Meena         HR      0.0
904    104      sai    Unknown  89000.0

**Day-6**

In [22]:
import pandas as pd
employees = {
    "EmpID": [101, 102, 103, 104,105],
    "Name": ["Asha", None, "Meena", "sai","sreedhar"],
    "Department": ["Sales", "IT", "HR", None,"Sales"],
    "Salary": [45000, 60000, None, 89000,95000]
}
I = [901, 902, 903, 904,905]
df = pd.DataFrame(employees, index = I)

In [23]:
#cleaning the data
df.isna()

     EmpID   Name  Department  Salary
901  False  False       False   False
902  False   True       False   False
903  False  False       False    True
904  False  False        True   False
905  False  False       False   False

In [24]:
df.isna()

     EmpID   Name  Department  Salary
901  False  False       False   False
902  False   True       False   False
903  False  False       False    True
904  False  False        True   False
905  False  False       False   False

In [25]:
df=df.fillna(
    {
        "Name":"Unknown",
        "Salary":0,
        "Department":"Unknown"
    }
)

In [26]:
print(df)

     EmpID      Name Department   Salary
901    101      Asha      Sales  45000.0
902    102   Unknown         IT  60000.0
903    103     Meena         HR      0.0
904    104       sai    Unknown  89000.0
905    105  sreedhar      Sales  95000.0

In [27]:
#group by
df.groupby("Department")["Salary"].mean()

Department
HR             0.0
IT         60000.0
Sales      70000.0
Unknown    89000.0
Name: Salary, dtype: float64

In [16]:
df.groupby("Department")["Salary"].min()

Department
HR             0.0
IT         60000.0
Sales      45000.0
Unknown    89000.0
Name: Salary, dtype: float64

In [17]:
df.groupby("Department")["Salary"].min()

Department
HR             0.0
IT         60000.0
Sales      45000.0
Unknown    89000.0
Name: Salary, dtype: float64

In [28]:
df.groupby("Department")["Salary"].agg(['mean','min','max'])

               mean      min      max
Department
HR              0.0      0.0      0.0
IT          60000.0  60000.0  60000.0
Sales       70000.0  45000.0  95000.0
Unknown     89000.0  89000.0  89000.0

In [ ]:
df.groupby("Department").agg({
    "Salary":['mean','min','max']

})

In [29]:
import pandas as pd
data={
    "Name":["Ravi","Priya","Arun","Sneha","Kiran","Anjali","Vikram","Meena"],
    "Age":[22,24,21,25,23,26,20,27],
    "City":["Hyd","Chennai","Banglore","Hyd","Mumbai","Chennai","Banglore","Mumbai"],
    "Salary":[30000,40000,28000,50000,35000,45000,25000,55000]
}

df=pd.DataFrame(data,index=[101,102,103,104,105,106,107,108])

In [30]:
print(df)

       Name  Age      City  Salary
101    Ravi   22       Hyd   30000
102   Priya   24   Chennai   40000
103    Arun   21  Banglore   28000
104   Sneha   25       Hyd   50000
105   Kiran   23    Mumbai   35000
106  Anjali   26   Chennai   45000
107  Vikram   20  Banglore   25000
108   Meena   27    Mumbai   55000

In [31]:
df["Name"]

101      Ravi
102     Priya
103      Arun
104     Sneha
105     Kiran
106    Anjali
107    Vikram
108     Meena
Name: Name, dtype: object

In [34]:
df[['Name','Salary']]

       Name  Salary
101    Ravi   30000
102   Priya   40000
103    Arun   28000
104   Sneha   50000
105   Kiran   35000
106  Anjali   45000
107  Vikram   25000
108   Meena   55000

In [35]:
df[df["Age"]>23]

       Name  Age     City  Salary
102   Priya   24  Chennai   40000
104   Sneha   25      Hyd   50000
106  Anjali   26  Chennai   45000
108   Meena   27   Mumbai   55000

In [36]:
df[df["Salary"]>40000]

       Name  Age     City  Salary
104   Sneha   25      Hyd   50000
106  Anjali   26  Chennai   45000
108   Meena   27   Mumbai   55000

In [37]:
df[df["City"]=="Chennai"]

       Name  Age     City  Salary
102   Priya   24  Chennai   40000
106  Anjali   26  Chennai   45000

In [39]:
df[(df["Age"]>22 )& (df["Salary"]>35000)]

       Name  Age     City  Salary
102   Priya   24  Chennai   40000
104   Sneha   25      Hyd   50000
106  Anjali   26  Chennai   45000
108   Meena   27   Mumbai   55000

In [40]:
df[(df["City"]=="Mumbai")|(df["City"]=="Banglore")]

       Name  Age      City  Salary
103    Arun   21  Banglore   28000
105   Kiran   23    Mumbai   35000
107  Vikram   20  Banglore   25000
108   Meena   27    Mumbai   55000

In [41]:
df[['Name','Salary']][df['Salary']>30000]

       Name  Salary
102   Priya   40000
104   Sneha   50000
105   Kiran   35000
106  Anjali   45000
108   Meena   55000

In [44]:
df.iloc[1:4]

      Name  Age      City  Salary
102  Priya   24   Chennai   40000
103   Arun   21  Banglore   28000
104  Sneha   25       Hyd   50000